matchMarketOrder function with fund transfer after match completion
elliottech/lighter-v1-core pull request #7
Opened 2023-04-06 15:33 UTC by kanthdefi

## Background:

## Change List:

- matchOrder function is to be refactored in to 2 functions:
    - matchLimitOrder
    - matchMarketOrder

- rename `matchOrder` function to `matchLimitOrder()`
- createNewOrder() to make use of new function `matchMarketOrder()`
- createLimitOrder() to make use of renamed `matchOrder()` to `matchLimitOrder()`

2023-04-06 15:42 UTC, kanthdefi commented on contracts/OrderBook.sol
> +    }
> Struct with localvars added to avoid stackTooDeep error
> matchMarketOrder() causing stackTooDeep error due to too-many local variables declared
> now this struct is created and most of local variables created and used in `matchMarketOrder()` will be set and accessed via the new struct

2023-04-06 15:43 UTC, kanthdefi commented on contracts/OrderBook.sol
> +    struct OrderMatchFill {
marketOrder is matched against the  limit orders in `bidOrderBook` or `askOrderBook` 
struct to capture the Fill during each match against limitOrders in OrderBook

-struct contains:
  - amount0 (matched)
  - amount`(matched)

2023-04-06 15:45 UTC, kanthdefi commented on contracts/OrderBook.sol
> +    function matchMarketOrder(
new function to match market Order

2023-04-06 15:46 UTC, kanthdefi commented on contracts/OrderBook.sol
> +                });
- initialize the OrderMatchFill 
- this contain the matched amount0, amount1
- address of marketMaker (from the limitOrder which is matched)

2023-04-06 15:49 UTC, kanthdefi commented on contracts/OrderBook.sol
> +        OrderMatchFill[] memory orderMatchFills = new OrderMatchFill[](100);
1. Local Array to hold the Matched fills for MarketOrder
2. Here we need to initialized with size, as  this as Array cant be used locally as memory  
3. Had it been in storage, we can keep it un-initialized and push the items to array later (this is not acceptable and efficient approach as storage operations are bad and super expensive for temporary local operations)

2023-04-06 15:50 UTC, kanthdefi commented on contracts/OrderBook.sol
> +    function matchLimitOrder(
1. renamed existing `matchOrder` to `matchLimitOrder`
2. Logic remains same for matching a LimitOrder

2023-04-07 09:25 UTC, eminayar requested changes

2023-04-07 09:25 UTC, eminayar commented on contracts/OrderBook.sol
> +                orderMatchFills[matchOrderLocalVars.orderMatchFillIndex] = orderMatchFill;
Can we explicitly initialize orderMatchFillIndex as 0 at the beginning of the function? I think it makes the code more readable for someone who is not familiar with solidity

2023-04-07 09:25 UTC, eminayar commented on contracts/OrderBook.sol
> +        OrderMatchFill[] memory orderMatchFills = new OrderMatchFill[](100);
What if it is a big order that can match with more than 100 orders?

2023-04-07 09:25 UTC, eminayar commented on contracts/OrderBook.sol
> +                    bool success = sendToken(token0, orderMatchFill.maker, orderMatchFill.matchAmount0);
Here we can't send the token from the contract to the maker since we didn't get the tokens from the taker yet. We can either `safeTransferFrom` taker to maker, or we can `safeTransferFrom` taker to the contract for the whole amount before the `for(uint ind = 0 ; ind < matchOrderLocalVars.orderMatchFillIndex ; ++ind)` and then send it using `sendToken`.

2023-04-07 09:27 UTC, kanthdefi commented on contracts/OrderBook.sol
> +        OrderMatchFill[] memory orderMatchFills = new OrderMatchFill[](100);
yeah we have this issue, we need to set a max value here to a number (max of uint332)
@eminayar

2023-04-07 09:27 UTC, kanthdefi commented on contracts/OrderBook.sol
> +                orderMatchFills[matchOrderLocalVars.orderMatchFillIndex] = orderMatchFill;
yeah will do it

2023-04-07 09:29 UTC, eminayar commented on contracts/OrderBook.sol
> +                    bool success = sendToken(token0, orderMatchFill.maker, orderMatchFill.matchAmount0);
Since the way we implemented the logic, users give approval to the router contract to avoid giving approval for each different order book. So we were using the `subtractSafeBalanceCallback` function to get users token to the order book. So considering this, you can call this function to get the tokens to the order book first and then distribute them

2023-04-07 09:29 UTC, kanthdefi commented on contracts/OrderBook.sol
> +                    bool success = sendToken(token0, orderMatchFill.maker, orderMatchFill.matchAmount0);
@eminayar started making this change
the approval is given for router contract
so we wouldn't be able to transfer between `taker` and `maker` directly
so should we add a function on `router` to do safeTransferFrom taker to maker?

2023-04-07 09:30 UTC, eminayar commented on contracts/OrderBook.sol
> +        OrderMatchFill[] memory orderMatchFills = new OrderMatchFill[](100);
Or you can iterate in batches. Meaning that after a batch is filled (100 orders in this case), process the payments and reset the array

2023-04-07 09:30 UTC, kanthdefi commented on contracts/OrderBook.sol
> +                    bool success = sendToken(token0, orderMatchFill.maker, orderMatchFill.matchAmount0);
or
i will use existing function `subtractSafeBalanceCallback` on `router` 
to transfer the sum of all fills from `taker` to `orderbook`
followed by sendToken for each loop iteration

2023-04-07 09:30 UTC, eminayar commented on contracts/OrderBook.sol
> +        OrderMatchFill[] memory orderMatchFills = new OrderMatchFill[](100);
I'm not sure which is more gas efficient. We can test it to see

2023-04-07 09:31 UTC, eminayar commented on contracts/OrderBook.sol
> +                    bool success = sendToken(token0, orderMatchFill.maker, orderMatchFill.matchAmount0);
That is another option. I don't see a down side of adding that functionality

2023-04-07 09:33 UTC, eminayar commented
Adding the market order tests to this PR makes sense. Can we also add user balance checks to the tests?

2023-04-07 09:33 UTC, kanthdefi commented on contracts/OrderBook.sol
> +        OrderMatchFill[] memory orderMatchFills = new OrderMatchFill[](100);
will first try with higher number and compute gas cost
followed by batch processing

2023-04-07 09:34 UTC, kanthdefi commented
> Adding the market order tests to this PR makes sense. Can we also add user balance checks to the tests?

@eminayar sure, at moment the balanceChecks are in for fallback transaction test
will add balance checks for maker and taker before and after making transaction

2023-04-07 13:59 UTC, ahmetavc commented on contracts/OrderBook.sol
> +                    bool success = sendToken(token0, orderMatchFill.maker, orderMatchFill.matchAmount0);
I don't see any reason to transfer tokens to order book here, it introduces extra step and increase the gas cost (which might be negligible though), so adding a safeTransferFrom callback to router seems good to me.

2023-04-07 13:59 UTC, ahmetavc commented on contracts/OrderBook.sol
> +        OrderMatchFill[] memory orderMatchFills = new OrderMatchFill[](100);
Another option here might be using a dynamic array, like copying values to 2x size array, but this might be same with batch processing in terms of gas efficiency. Let's try one of these and not use a strict number here. (Or we can put a strict limit to the array size if we are confident that the limit correlates with gas limit of the block)

2023-04-10 12:15 UTC, muratekici commented on contracts/OrderBook.sol
> +        OrderMatchFill[] memory orderMatchFills = new OrderMatchFill[](100);
i don't think we should create extra constraints such as 100 max matching etc. 100 orders is probably not practical right now but it will be when proto dank sharding comes. We can talk further on this,

2023-04-21 09:54 UTC, closed without merging